{"name": "Editar Funcionário", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[contains(text(), 'Alterar')]\"}\n  (Session info: chrome=131.0.6778.264); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x55a9d68a41fa <unknown>\n#1 0x55a9d63b4810 <unknown>\n#2 0x55a9d6403506 <unknown>\n#3 0x55a9d64037a1 <unknown>\n#4 0x55a9d6448c24 <unknown>\n#5 0x55a9d64275ad <unknown>\n#6 0x55a9d6446007 <unknown>\n#7 0x55a9d6427323 <unknown>\n#8 0x55a9d63f5de0 <unknown>\n#9 0x55a9d63f6dbe <unknown>\n#10 0x55a9d687012b <unknown>\n#11 0x55a9d68740c7 <unknown>\n#12 0x55a9d685d6cc <unknown>\n#13 0x55a9d6874c47 <unknown>\n#14 0x55a9d684267f <unknown>\n#15 0x55a9d6893288 <unknown>\n#16 0x55a9d6893450 <unknown>\n#17 0x55a9d68a3076 <unknown>\n#18 0x7ff6a5567112 <unknown>\n\n", "trace": "  File \"/home/fish/git/python-automation/.venv/lib/python3.12/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/fish/git/python-automation/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/homepage_steps.py\", line 47, in step_impl\n    text_element = context.browser.find_element(By.XPATH, f\"//*[contains(text(), 'Alterar')]\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/fish/git/python-automation/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 888, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/fish/git/python-automation/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/fish/git/python-automation/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given O usuário está na página do portal de testes SEA Tecnologia", "status": "passed", "attachments": [{"name": "Screenshot", "source": "f5e5469f-485f-42cd-85b5-fd0079baee4a-attachment.png", "type": "image/png"}], "start": 1737609474915, "stop": 1737609475077}, {"name": "When O menu de opções do funcionário é selecionado", "status": "passed", "attachments": [{"name": "Screenshot", "source": "c8748098-c3ce-446c-b298-d5d2dcd0bd3c-attachment.png", "type": "image/png"}], "start": 1737609475077, "stop": 1737609475304}, {"name": "Then A opção Editar funcionário é selecionada", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[contains(text(), 'Alterar')]\"}\n  (Session info: chrome=131.0.6778.264); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x55a9d68a41fa <unknown>\n#1 0x55a9d63b4810 <unknown>\n#2 0x55a9d6403506 <unknown>\n#3 0x55a9d64037a1 <unknown>\n#4 0x55a9d6448c24 <unknown>\n#5 0x55a9d64275ad <unknown>\n#6 0x55a9d6446007 <unknown>\n#7 0x55a9d6427323 <unknown>\n#8 0x55a9d63f5de0 <unknown>\n#9 0x55a9d63f6dbe <unknown>\n#10 0x55a9d687012b <unknown>\n#11 0x55a9d68740c7 <unknown>\n#12 0x55a9d685d6cc <unknown>\n#13 0x55a9d6874c47 <unknown>\n#14 0x55a9d684267f <unknown>\n#15 0x55a9d6893288 <unknown>\n#16 0x55a9d6893450 <unknown>\n#17 0x55a9d68a3076 <unknown>\n#18 0x7ff6a5567112 <unknown>\n\n", "trace": "  File \"/home/fish/git/python-automation/.venv/lib/python3.12/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/fish/git/python-automation/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/homepage_steps.py\", line 47, in step_impl\n    text_element = context.browser.find_element(By.XPATH, f\"//*[contains(text(), 'Alterar')]\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/fish/git/python-automation/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 888, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/fish/git/python-automation/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/fish/git/python-automation/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "attachments": [{"name": "Screenshot", "source": "304a5c3e-25a2-4f94-b79c-f2580840eaf8-attachment.png", "type": "image/png"}], "start": 1737609475304, "stop": 1737609475439}], "attachments": [{"name": "Screenshot", "source": "ba723932-a8d6-4507-a680-e275991b6bc7-attachment.png", "type": "image/png"}], "start": 1737609474133, "stop": 1737609475610, "uuid": "334e8e4a-04fd-46e5-b50f-51b88a5f3a3d", "historyId": "4df2aeaa3c44e60a05ad289d353d5f9c", "fullName": "Editar Funcionário: Editar Funcionário", "labels": [{"name": "epic", "value": "HomePage"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "Labels"}, {"name": "tag", "value": "ok"}, {"name": "feature", "value": "Editar Funcionário"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}